config/routes.rb
Rails.application.routes.draw do

  resources :topics

  resources :asks do 
      resources :replies
    end
  get '/asks/:ask_id/replies/edit/:id' => 'replies#edit'
  mount Attachinary::Engine => "/attachinary"
  devise_for :users, controllers: {
        sessions: 'users/sessions',
   registrations: 'users/registrations' }
    
  root to: 'pages#home'
  



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


    get 'ask/index'
    


  get "/team" => "pages#team"
  get "/contact" => "pages#join_us"


  get "/courses" => "courses#index"
  get "/courses/new" => "courses#new"
  get "/courses/:id" => "courses#show"


  resources :courses
  resources :users
   devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :comments, only: :create




end

app/models/reply.rb
class Reply < ApplicationRecord
	belongs_to :ask
	belongs_to :user

	validates :reply, presence: true 
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
	before_action :authenticate_user!
	before_action :set_reply, only: [:edit, :update, :show, :destroy]
	before_action :set_ask, only: [:create, :edit, :show, :update, :destroy]



	def create
		@reply = @ask.replies.create(params[:reply].permit(:reply, :ask_id))
		@reply.user_id = current_user.id

		respond_to do |format|
			if @reply.save
				format.html {redirect_to ask_path(@ask)}
				format.js #render create.js.erb
			else
		format.html { redirect_to ask_path(@ask), notice: 'Reply did not save'}
		format.js
			end
		end
	end


	def new

	end

	def destroy
		@reply = @ask.replies.find(params[:id])
		@reply.destroy
		redirect_to ask_path(@ask)
	end

	 def edit
	 	puts "%%%% params: #{params.inspect}"
    @ask = Ask.find(params[:ask_id])
    @reply = @ask.replies.find(params[:id])
  	end

  	def update
  		@repy = @ask.replies.find(params[:id])
  		respond_to do |format|
  			if @reply.update(reply_params)
  				format.html {redirect_to ask_path(@ask), notice: 'Reply successfully updated'}
  			else
        		format.html { render :edit }
        		format.json { render json: @reply.errors, status: :unprocessable_entity }
      		end
      	end
  	end

  	def show
  	end

	private

	def set_ask 
		@ask = Ask.find(params[:ask_id])
	end

	def set_reply
		@reply = Reply.find(params[:id])
	end

	def reply_params
		params.require(:reply).permit(:reply)
	end
end

app/views/replies/_form.html.erb
<%= simple_form_for([@ask, @ask.replies.build], remote: true) do |f| %>

<div class="field">
  <div class="control">
    <%= f.input :reply, input_html: { class: 'textarea' }, wrapper: false, label_html: { class: 'label' } %>
  </div>
</div>

<%= f.button :submit, 'Give a recommendation', class:'button is-info' %>

<% end %>

app/views/replies/_reply.html.erb
<div class="box">
  <article class="media">
    <div class="media-left">
      <figure class="image is-48x48">
        <%= gravatar_image_tag(reply.user.email, class: 'border-radius-50', size: 48, alt: reply.user.username) %>
      </figure>
    </div>
    <div class="media-content">
      <div class="content">
        <p>
          <strong><%= reply.user.username %></strong> <small><%= time_ago_in_words(reply.created_at) %></small>
          <br/>
          <%= reply.reply %>
        </p>
      </div>
      <% if reply_author(reply) || has_role?(:admin) %>
      <nav class="level is-mobile">
        <div class="level-left">
          <a class="level-item">
            <%= link_to edit_ask_reply_path(reply.ask, reply) do %>
            <%#= link_to [reply.ask, reply] do %>
            <span class="icon is-small"><i class="fa fa-pencil"></i></span>
            EDIT
            <% end %>
          </a>
          <a class="level-item">
            <%= link_to ask_reply_path(reply.ask, reply),
                method: :delete, data: {confirm: "Are you sure ?" } do %>
            <span class="icon is-small"><i class="fa fa-trash-o"></i></span>
            <% end %>
          </a>
        </div>
      </nav>
      <% end %>
    </div>
  </article>
</div>

app/views/replies/create.js.erb
$("<%= escape_javascript(render(@reply)) %>").appendTo('#ask-replies');

app/views/replies/edit.html.erb
<h1 class="title is-2 has-text-grey">Editing Reply</h1>

<%= simple_form_for([@ask, @reply]) do |f| %>
<div class="field">
  <div class="control">
    <%= f.input :reply, input_html: { class: 'textarea' }, wrapper: false, label_html: { class: 'label' } %>
  </div>
</div>

  <%= f.button :submit, 'Update reply', class:'button is-info' %>
<% end %>