config/routes.rb
Rails.application.routes.draw do

  resources :topics

  resources :asks do 
      resources :replies
    end
  get '/asks/:ask_id/replies/edit/:id' => 'replies#edit'
  mount Attachinary::Engine => "/attachinary"
  devise_for :users, controllers: {
        sessions: 'users/sessions',
   registrations: 'users/registrations' }
    
  root to: 'pages#home'
  



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


    get 'ask/index'
    


  get "/team" => "pages#team"
  get "/contact" => "pages#join_us"


  get "/courses" => "courses#index"
  get "/courses/new" => "courses#new"
  get "/courses/:id" => "courses#show"


  resources :courses
  resources :users
   devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :comments, only: :create




end

app/models/ask.rb
class Ask < ApplicationRecord
	belongs_to :topic
	belongs_to :user
	has_many :replies, dependent: :destroy
	

	validates :title, :content, :topic_id, presence: true
end

app/controllers/asks_controller.rb
class AsksController < ApplicationController
  before_action :set_ask, only: [:show, :edit, :update, :destroy]
  before_action :find_topics, only: [:index, :show, :new, :edit]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /asks
  # GET /asks.json
  def index
    @asks = Ask.all.order('created_at desc')
  end

  # GET /asks/1
  # GET /asks/1.json
  def show
    @asks = Ask.all.order('created_at desc')
    @ask = Ask.find(params[:id])
  end

  # GET /asks/new
  def new
    @ask = current_user.asks.build
  end

  # GET /asks/1/edit
  def edit
  end

  # POST /asks
  # POST /asks.json
  def create
    @topics  = Topic.all
    @ask = current_user.asks.build(ask_params)
    respond_to do |format|
      if @ask.save
        format.html { redirect_to @ask, notice: 'Ask was successfully created.' }
        format.json { render :show, status: :created, location: @ask }
      else
        format.html { render :new }
        format.json { render json: @ask.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /asks/1
  # PATCH/PUT /asks/1.json
  def update
    respond_to do |format|
      if @ask.update(ask_params)
        format.html { redirect_to @ask, notice: 'Ask was successfully updated.' }
        format.json { render :show, status: :ok, location: @ask }
      else
        format.html { render :edit }
        format.json { render json: @ask.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /asks/1
  # DELETE /asks/1.json
  def destroy
    @ask.destroy
    respond_to do |format|
      format.html { redirect_to asks_url, notice: 'Ask was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ask
      @ask = Ask.find(params[:id])
    end

    def find_topics
      @topics = Topic.all.order('created_at desc')
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ask_params
      params.require(:ask).permit(:title, :content, :topic_id)
    end
end

app/helpers/asks_helper.rb
module AsksHelper

  def ask_author(ask)
    user_signed_in? && current_user.id == ask.user_id
  end

  def reply_author(reply)
    user_signed_in? && current_user.id == reply.user_id
  end

end

app/views/asks/_ask.html.erb
<div class="column is-8">
  <h3 class="title is-5 has-text-grey-light">Latest Discussions</h3>

  <div class="asks">
<%= link_to 'Ask Recommendation', new_ask_path, class:'button is-info' %>
<hr />

    <% @asks.each do |ask| %>
      <div class="columns bb-not-last pv10">
        <div class="column is-1">
          <img src="http://placehold.it/60x60" alt="" class="avatar ask">



        </div>
        <div class="column is-8">
          <%= link_to ask do %>
            <h3 class="title is-5"><%= ask.title %></h3>
          <% end %>
          <div class="content">
            <%= truncate(ask.content, length: 140) %>
            <p><em><small><%= time_ago_in_words(ask.created_at) %> ago in
              <% if ask.topic.present? %>
                <%= link_to ask.topic.topic, ask.topic %>
              <% end %>
              by <%= link_to ask.user.username unless ask.user.blank?   %>
              </small>
              </em>
            </p>
          </div>
        </div>

        <% # if  ask_author(ask) || has_role?(:admin) %>
        <div class="column has-text-right">
          <%= link_to 'Edit', edit_ask_path(ask), class:'button' %>
          <%= link_to 'Delete', ask, method: :delete, data: { confirm: 'Are you sure?' }, class: "button" %>
        </div>
        <% # end %>

      </div>
    <% end %>
    
  </div>
</div>

app/views/asks/_form.html.erb
<%= simple_form_for(@ask) do |f| %>
  <%= f.error_notification %>

<h1>Ask recommendation</h1>  

  <div class="field question">
    <div class="control">
      <%= f.input :title, required: true, input_html: { class: 'input' }, wrapper: false, label_html: { class: "label" }, placeholder: "Ask for a course recommendation - ex: What is the best course to work as a travel video maker ?" %>
    </div>
  </div>

  <div class="field description">
    <div class="control">
      <%= f.input :content, required: true, input_html: { class: 'textarea' }, wrapper: false, label_html: { class: "label" }, placeholder: "Add context or clarification - ex: I'm looking for a course to work with tourism industry and market my skills" %>
    </div>
  </div>

  <div class="field wtopic">
    <label class="label">Channel</label>
    <div class="control has-icons-left">
      <span class="select">
        <%= f.input_field :topic_id, collection:@topics.map { |c| [c.topic, c.id] }, prompt: "Select topic" %>
      </span>
      <span class="icon is-small is-left">
        <i class="fa fa-tag"></i>
      </span>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= f.button :submit, class:"button is-info" %>
    </div>
  </div>

<%= link_to 'Back', asks_path %>
<% end %>

app/views/asks/_sidebar.html.erb
<div class="column is-2 is-offset-1">
  <h3 class="title is-5 has-text-grey-light">Channels</h3>

  <ul class="list">
    <% @topics.each do |c| %>
    <li><%= link_to c.topic, c %></li>
    <% end %>
  </ul>

  <br/>

  <% # if has_role?(:admin) %>
  <%= link_to 'New Channel', new_topic_path, class:'button is-info' %>
  <% # end %>

</div>

app/views/asks/edit.html.erb
<h1>Editing Ask</h1>

<%= render 'form', ask: @ask %>

<%= link_to 'Show', @ask %> |
<%= link_to 'Back', asks_path %>

app/views/asks/index.html.erb
<div class="columns">
	<%= render 'sidebar' %>
  <%= render 'ask' %>
  
</div>

app/views/asks/new.html.erb
<!-- <h1>New Ask</h1> -->

<%= render 'form', ask: @ask %>

<!-- <%= link_to 'Back', asks_path %> -->

app/views/asks/show.html.erb
<div class="columns">



  <div class="column is-8 ask">






  	<div class="ask-heading">	
  		<div class="ask-heading-user">
  			<div class="ask-heading-user-image">
  				<a><img src="http://placehold.it/60x60" alt="" class="avatar ask"></a>
  			</div>

  				<div class="ask-heading-user-info">
  					
  						<%= link_to @ask.user.username unless @ask.user.blank? %>
  						<span>User tagline</span>
  				</div>
  			</div>
  			<div class="ask-heading-topic">
  				<%= link_to @ask.topic.topic , @ask.topic %>
  			</div>
  		</div>

  		<% if ask_author(@ask) %>
        <div class="buttons ask-controls">
            <%= link_to 'Edit Discussion', edit_ask_path(@ask), class:'button'%>
            <%= link_to 'Delete', ask_path(@ask), method: :delete, data: { confirm: "Delete ask?" }, class:'button' %>
        </div>
        <% end %>


    <h1 class="title is-2 has-text-grey ask-title ask-title"><%= @ask.title %></h1>
    
    <div class="level">
      <div class="level-left"></div>
      <div class="level-right">
        
      </div>
    </div>
    <div class="content ask-content"><%= @ask.content %></div>

<h2 class="subtitle is-5 has-text-grey ask-reply-info"><%=  @ask.replies.count %> Replies</h2>

    <div id="ask-replies">

       <%= render @ask.replies %> 
 </div> 

    <hr />

   <h3 class="subtitle is-3 has-text-grey ask-leaveareply">Leave a reply</h3>
     <%  if user_signed_in? %>
      <%=   render 'replies/form' %>
    <%  else %>
    <p>To reply you need to <%= link_to 'login', new_user_session_path %>. Don't have an account?
      <%= link_to 'Sign up', new_user_registration_path %> for one.</p>
    <%  end %>  

  </div> 

  <%= render 'sidebar' %>

</div>