config/routes.rb
Rails.application.routes.draw do

  resources :topics

  resources :asks do 
      resources :replies
    end
  get '/asks/:ask_id/replies/edit/:id' => 'replies#edit'
  mount Attachinary::Engine => "/attachinary"
  devise_for :users, controllers: {
        sessions: 'users/sessions',
   registrations: 'users/registrations' }
    
  root to: 'pages#home'
  



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


    get 'ask/index'
    


  get "/team" => "pages#team"
  get "/contact" => "pages#join_us"


  get "/courses" => "courses#index"
  get "/courses/new" => "courses#new"
  get "/courses/:id" => "courses#show"


  resources :courses
  resources :users
   devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :comments, only: :create




end

app/models/topic.rb
class Topic < ApplicationRecord
	belongs_to :ask

	has_many :asks
	has_many :users, through: :asks
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
    @asks = Ask.all.order('created_at desc')
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    @asks = Ask.where('topic_id = ?', @topic.id)
    @topics = Topic.all
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    puts " %%%% #{topic_params.inspect}"
    @topic = Topic.new(topic_params)  
    @ask.topic = @topic

    respond_to do |format|
      if @topic.save
        format.html { redirect_to topics_path, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topics_path, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:topic)
    end
end

app/views/topics/_form.html.erb
<% if false %>

<%= simple_form_for(@topic) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :topic %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

<% else %>

<%= simple_form_for(@topic) do |f| %>
  <%= f.error_notification %>

 <div class="field">
   <div class="control">
     <%= f.input :name, input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' } %>
   </div>
 </div>

 <%= f.button :submit, class: 'button is-info' %>
<% end %>

<% end %>

app/views/topics/edit.html.erb
<h1>Editing Topic</h1>

<%= render 'form', topic: @topic %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="title is-2">Channels</h1>

<% # if has_role?(:admin) %>
<div class="level">
  <div class="level-left"></div>
  <div class="level-right">
    <%= link_to 'New Channel', new_topic_path, class:'button is-dark' %>
  </div>
</div>

<table class="table is-fullwidth">
  <thead>
    <tr>
      <th>Channel</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @topics.each do |topic| %>
    <tr>
      <td><%= link_to topic.topic, topic %></td>
      <td>
        <div class="buttons is-right">
          <%= link_to 'View Channel', topic, class:'button' %>
          <%= link_to 'Edit Channel', edit_topic_path(topic), class:'button' %>
          <%= link_to 'Delete', topic, class:'button is-danger', method: :delete, data: { confirm: "Are you sure you want to delete this topic? " } %>
        </div>
      </td>
    </tr>
    <% end %>
  </tbody>

</table>

<% #else %>
 <!-- <p class="has-text-center">Sorry! You don't have access this page.</p> -->
<% #end %>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<%= render 'form', topic: @topic %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Topic:</strong>
  <%= @topic.topic %>
</p>

<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Back', topics_path %>