config/routes.rb
Rails.application.routes.draw do

  resources :topics

  resources :asks do 
      resources :replies
    end
  get '/asks/:ask_id/replies/edit/:id' => 'replies#edit'
  mount Attachinary::Engine => "/attachinary"
  devise_for :users, controllers: {
        sessions: 'users/sessions',
   registrations: 'users/registrations' }
    
  root to: 'pages#home'
  



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


    get 'ask/index'
    


  get "/team" => "pages#team"
  get "/contact" => "pages#join_us"


  get "/courses" => "courses#index"
  get "/courses/new" => "courses#new"
  get "/courses/:id" => "courses#show"


  resources :courses
  resources :users
   devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :comments, only: :create




end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
    <%= image_tag "/assets/images/logo.png" %> <!-- image_path /url -->
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right">

   
      
        <%= link_to "All courses", courses_path, class: "navbar-wagon-item navbar-wagon-link" %>

  
    <a href="" class="navbar-wagon-item navbar-wagon-link">Browse by Jobs</a>

<% if user_signed_in? %>

    <%= link_to "Ask Recommendations", asks_path %>

      <div class="btn btn-success"><%= link_to "Add a course", new_course_path, class:"navbar-wagon-item navbar-wagon-button btn btn-success" %> </div>




    <!-- Profile picture with dropdown list -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <img src="https://kitt.lewagon.com/placeholder/users/ssaunier" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to "Profile", edit_user_registration_path %> </a></li>
          <li><a href="#">Wishlist</a></li>
          <li><%= link_to "Ask Recommendations", asks_path %></li>
          <li><a href="#">Orientation Test</a></li>
          <li><a href="#">Reference a course</a></li>
          <li><a href="#">Paths & My learning Plans</a></li>
          <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %> </li>

        </ul>
      </div>
   

  <!-- Button, call to action -->

 

<% else %>

<%= link_to "Connexion", new_user_session_path %>
<%= link_to "Inscription", new_user_registration_path %>

<% end %>

 </div>
  </div>

  <!-- Dropdown appearing on mobile only 
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Host</a></li>
        <li><a href="#">Trips</a></li>
        <li><a href="#">Messagese</a></li>
      </ul>
    </div>
  </div> -->
</div> 